db.url=jdbc:sqlserver://localhost:1433;databaseName=tiendaonline;encrypt=true;trustServerCertificate=true;
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.credentials.file=config/db_credentials.txt
